POST http://localhost:8088/admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "banyuan"
}

> {% client.global.set("auth_token", response.body.data.token) %}

###

GET http://localhost:8088/admin/auth
Content-Type: application/json
Authorization: bearer{{auth_token}}

###

GET http://localhost:8088/admin/list?keyWords=管理&pageNum=1&pageSize=5
Content-Type: application/json
Authorization: bearer{{auth_token}}
###
