server:
  port: 8088

security:
  ignored:
    urls:
      - /admin/login
      - /register/**
      - /login
      - /index
      - /static/**
      - /webjars/**
token:
  secretKey: GuessWhatTheCodeIs
  expireSec: 3600